# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Configuration du service d'importation d'icônes
    App\Service\IconImportService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    # Configuration du listener pour l'importation automatique d'icônes
    App\EventListener\TechnologyIconListener:
        tags:
            - { name: 'doctrine.event_listener', event: 'postPersist' }
            - { name: 'doctrine.event_listener', event: 'postUpdate' }

    # Configuration du QuoteService avec injection d'AuditService
    App\Service\QuoteService:
        calls:
            - [setAuditService, ['@App\Service\AuditService']]

    # Configuration du InvoiceService avec injection d'AuditService
    App\Service\InvoiceService:
        calls:
            - [setAuditService, ['@App\Service\AuditService']]

    # Configuration du MagicLinkService pour les liens signés
    App\Service\MagicLinkService:
        arguments:
            $appSecret: '%env(APP_SECRET)%'

    App\Service\PaymentService:
        arguments:
            $stripeSecretKey: '%env(default::STRIPE_SECRET_KEY)%'

    App\Controller\StripeWebhookController:
        arguments:
            $stripeWebhookSecret: '%env(default::STRIPE_WEBHOOK_SECRET)%'

    App\Controller\Public\DebugMagicLinkController:
        arguments:
            $appSecret: '%env(APP_SECRET)%'


